name: Slack Notification
run-name: ${{ github.actor }} notify slack 🚀

on:
  workflow_call:
    inputs:
      title:
        require: true
        type: string
      status:
        require: true
        type: string
      commit_url:
        require: true
        type: string
    secrets:
      webhook_url:
        require: true
        type: string

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notifications
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "${{ inputs.title }}: ${{ inputs.status }}\n${{ inputs.commit_url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.title }}: ${{ inputs.status }}\n${{ inputs.commit_url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CI_TEST_SLACK_WEBHOOK_URL }}
